### ISSUE TITLE
Investigate failing TCK tests

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-sdk-tck#16]
### Description

The TCK has completed its job. The newest versions of the SDK are falling against some tests. We were thinking that this is a problem with the Local Node, but actually is something with the SDK. We are working with Antonio,  Emanuel and me to fix it.

### Steps to reproduce

![Screenshot 2023-08-01 at 11 54 30](https://github.com/hashgraph/hedera-sdk-tck/assets/21989138/db35e022-2b83-4570-989f-f1b0d80eb880)

### Hedera network

testnet

### Version

0

### Operating system

None

**Comment by SimiHunjan** [comment]
Created this issue to track the resolution on why the tests run by the TCK are failing.

**Comment by ochikov** [comment]
It's resolved in the new version of the TCK with merged PR from @bamzedev.
