### ISSUE TITLE
Create new test file for `AccountUpdateTransaction` and remove `test_UpdateAccountKey.js`, `test_UpdateAccountMeme.js` 

### ISSUE THREAD

**Issue by agadzhalov** [hashgraph/hedera-sdk-tck#196]
- test_UpdateAccountKey.js -> to be removed 🗑
- test_UpdateAccountMeme.js -> to be removed 🗑
- Create new file `accountUpdateTransaction.js` which will implement the logic from `test_UpdateAccountKey.js`  and `test_UpdateAccountMeme.js`

**Comment by rwalworth** [comment]
The work for this is done in #224. Once that is merged, this can be closed.

**Comment by rwalworth** [comment]
#224 was merged, closing this.
