### ISSUE TITLE
AccountDelete test not working correctly

### ISSUE THREAD

**Issue by gsstoykov** [hashgraph/hedera-sdk-tck#198]
### Description

The test is creating an account and then deletes it which should trigger a send of tokens from the account being deleted but that account is always created with zero balance. One of the the test checks if there was a successful token transfer.
```
 let response = await JSONRPCRequest("createAccount", {
      publicKey: newPublicKey,
    });
```

```
 assert.strictEqual(
      recipientFinalBal,
      newAccountBal + recipientInitialBal,
      "new recipientAccount bal is its initial bal + the deleted account's closing bal "
    );
```

### Steps to reproduce

The problematic test code can be found int `test_AccountDelete.js`

### Hedera network

testnet

### Version

v0.0.0

### Operating system

None

**Comment by rwalworth** [comment]
#230 redid `AccountDeleteTransaction` tests and all are in working order. Closing this as it is no longer relevant.
